tabWidth: 2
overrides:
  - files: "*.djt"
    options:
      parser: "html"
      requirePragma: true
      printWidth: 120
  - files: "*.html"
    options:
      requirePragma: true
      printWidth: 120
