---
name: Michael Van Wickle
url: "https://wherewasigoing.com"
repository: mvwicky/mvwicky.github.io
title: "Where Was I Going With That?"
description: "A blog, which generally consists of posts that are lists of links, followed by thoughts on said links"
permalink: /blog/:year/:month/:day/:title
future: false
strict_front_matter: true
lsi: true
defaults:
  - scope:
      path: ""
    values:
      layout: default
      excerpt_separator: <!--excerpt-->
exclude:
  - .cache/
  - ".git*"
  - "*.json"
  - "*.log"
  - "*.py"
  - "*.sublime-*"
  - bin/
  - Gemfile.lock
  - Makefile
  - README.md
  - src/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - webpack.config.ts
  - yarn.lock
  - requirements-dev.txt
include:
  - _headers
plugins:
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-seo-tag
  - classifier-reborn
author:
  name: Michael Van Wickle
twitter:
  username: mvwicky
  card: summary

sass:
  style: compressed
kramdown:
  math_engine: mathjax
  show_warnings: true
jekyll_compose:
  default_front_matter:
    drafts:
      layout: somelinks
      tags: [links]
