[build]
  publish = "_site/"
  command = "make build"

[build.environment]
  YARN_VERSION = "1.21.0"

[[headers]]
  for = "/dist/sw.js"
  [headers.value]
    service-worker-allowed = "/"
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''

[[headers]]
  for = "/dist/main.*.js"
  [headers.values]
    cache-control = '''
    max-age=604800,
    public,
    immutable'''

[[headers]]
  for = "/dist/style.*.css"
  [headers.values]
    cache-control = '''
    max-age=604800,
    public,
    immutable'''

[[headers]]
  for = "/dist/manifest.json"
  [headers.values]
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
