[build]
  publish = "_site/"
  command = "make build"

[[headers]]
  for = "/dist/*.*.js"
  [headers.values]
    cache-control = '''
    max-age=604800,
    public,
    immutable'''

[[headers]]
  for = "/dist/*.*.css"
  [headers.values]
    cache-control = '''
    max-age=604800,
    public,
    immutable'''

[[headers]]
  for = "/dist/manifest.json"
  [headers.values]
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''